name: Test and Deploy DefiVault Contract

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx hardhat test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Upload SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: deploy_key
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Connect to EC2 and start Hardhat node
        run: |
          ssh -i deploy_key -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            cd ~/defi-vault
            npx hardhat node --fork "https://api.avax.network/ext/bc/C/rpc" --hostname 172.31.29.252 &

            # Wait for Hardhat node to start
            sleep 30
          EOF

      - name: Deploy contract
        run: |
          ssh -i deploy_key -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            cd ~/defi-vault
            npx hardhat ignition deploy ./ignition/modules/DefiVault.ts --network hardhat
          EOF
